apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}-provider-access-keys
  namespace: {{ .Values.federationNamespace }}
type: Opaque
data:
  {{ if .Values.awsAccessKeyId }}
  awsAccessKeyId: {{ .Values.awsAccessKeyId | b64enc | quote }}
  {{ end }}
  {{ if .Values.awsSecretAccessKey }}
  awsSecretAccessKey: {{ .Values.awsSecretAccessKey | b64enc | quote }}
  {{ end }}
  {{ if .Values.okeBearerToken }}
  okeBearerToken: {{ .Values.okeBearerToken | b64enc | quote }}
  {{ end }}
  {{ if .Values.okeAuthGroup }}
  okeAuthGroup: {{ .Values.okeAuthGroup | b64enc | quote }}
  {{ end }}
  {{ if .Values.okeCloudAuthId }}
  okeCloudAuthId: {{ .Values.okeCloudAuthId | b64enc | quote }}
  {{ end }}